apiVersion: v1
kind: Service
metadata:
  name: my-python-simple-app-svc
  labels:
    app: python-simple-app
spec:
  type: NodePort
  selector:
    app: python-simple-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8000
      targetPort: 8000
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-simple-deployment
  labels:
    app: python-simple-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-simple-app
  template:
    metadata:
      labels:
        app: python-simple-app
    spec:
      containers:
      - name: python-simple-app
        image: kanchimo/python-simple-app:8
        ports:
        - containerPort: 8000
